### ISSUE TITLE
changing commemts

### ISSUE THREAD

**Issue by Noammazouz** [YanivGabay/CodeFiles-intro_to_cs_Yaniv_lectures#6]
%i is only for integar reguler one
%o is for octal integer.
%x is for hexadecimal integer.

**Comment by Noammazouz** [comment]
to clearfy in line 63 you wrote that %i is for integer that can be octa, hexa or dec but base on what I sew on https://en.cppreference.com/w/c/io/fscanf is says that you need to use %0 for octa and %x for hexa.

**Comment by YanivGabay** [comment]
![image](https://github.com/user-attachments/assets/6cf1189f-d974-4b0f-9e6f-54df1f8dd40b)

בעצם יכול לקבל את שלושתם בהתאם לפריקס שמקבלים במספר לדוגמא: 0xFAFA יקלוט את המספר כהקסה, ה0 והX הם ספציפיים רק עבור קלט מהסוג הנ"ל
